name: Create release tag

on:
  push:
    paths: [ emscripten-releases-tags.json, .github/workflows/tag-release.yml ]
  workflow_dispatch:

jobs:
    tag-release:
      runs-on: ubuntu-latest
      steps:
        - name: Get Release number
          uses: actions/github-script@v7
          with:
            script: |
              const commit = await github.rest.git.getCommit({
                owner: context.repo.owner,
                repo: context.repo.repo,
                commit_sha: context.sha
              })
              console.log(commit)
              console.log("message")
              const message = "${{ github.event.head_commit.message }}"
              console.log(message)
              const regex = /Release ([0-9]+.[0-9]+.[0-9]+)/
              const match = message.match(regex)
              if (match) {
                console.log(`Matched release ${match[1]}`)
              } else {
               console.log("no match")
              }
        - name: Create tag
          uses: actions/github-script@v7
          with:
            script: |
              github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: 'refs/tags/TAGNAME',
                sha: context.sha
              })